DROP DATABASE IF EXISTS class_app;
CREATE DATABASE class_app;
USE class_app;

CREATE TABLE students (id INT NOT NULL AUTO_INCREMENT, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL, password VARCHAR(100) NOT NULL, registeredIds VARCHAR(100), droppedIds VARCHAR(100),PRIMARY KEY(id));

CREATE TABLE classes (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(100) NOT NULL, code CHAR(7) NOT NULL, semester VARCHAR(20) NOT NULL, tuition FLOAT NOT NULL DEFAULT 1783.38, availableSpaces INT NOT NULL, description VARCHAR(1000) NOT NULL, PRIMARY KEY(ID));


